version: "3.5"

networks:
    kong-net:
        driver: bridge
        name: kong-net
        
services:
    rabbitmq:
        build:
            context: ./
            dockerfile: Dockerfile-rabbitmq
        image: esd-rabbitmq:3.6
        container_name: rabbitmq_container
        networks:
            - kong-net

    kong:
        build:
            context: ./
            args:
                JWT_SECRET: ${JWT_SECRET}
                JWT_KEY: ${JWT_KEY}
            dockerfile: Dockerfile-kongnodb
        image: kong_nodb:1.0
        container_name: kong_nodb
        networks:
            - kong-net
        environment:
            KONG_DATABASE: "off"
            KONG_DECLARATIVE_CONFIG: kong.yml
            KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        ports:
            - "8000:8000/tcp"
            - "8001:8001/tcp"
            - "8443:8443/tcp"
            - "8444:8444/tcp"
            
    mysqldb:
        image: mysql:8.0
        container_name: mysql_container
        volumes:
            - ./mysql-init-files:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - kong-net
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    
    user:
        build:
            context: ./User
        environment:
            RABBITMQ_HOSTNAME: "rabbitmq"
            RABBITMQ_PORT: "5672"
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            JWT_SECRET: ${JWT_SECRET}
            JWT_KEY: ${JWT_KEY}
            PYTHONUNBUFFERED: 1
        image: user:1.0
        container_name: user_container
        networks:
            - kong-net
        depends_on:
            - mysqldb
            - rabbitmq
        restart: always
    
    activity-log:
        build:
            context: ./ActivityLog
        environment:
            RABBITMQ_HOSTNAME: "rabbitmq"
            RABBITMQ_PORT: "5672"
            LOGDNA_INGESTION: ${LOGDNA_INGESTION}
            PYTHONUNBUFFERED: 1
        image: activity-log:1.0
        container_name: activity_log_container
        networks:
            - kong-net
        depends_on:
            - rabbitmq
        restart: always

    send-email:
        build:
            context: ./SendEmail
        environment:
            RABBITMQ_HOSTNAME: "rabbitmq"
            RABBITMQ_PORT: "5672"
            EMAIL_USERNAME: ${EMAIL_USERNAME}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            PYTHONUNBUFFERED: 1
        image: send-email:1.0
        container_name: send_email_container
        networks:
            - kong-net
        depends_on:
            - rabbitmq
        restart: always

    protected-endpoint:
        build:
            context: ./boilerplate-protected-endpoint
        environment:
            PYTHON_ENV: PROD
            RABBITMQ_HOSTNAME: "rabbitmq"
            RABBITMQ_PORT: "5672"
            PYTHONUNBUFFERED: 1
        image: protected-endpoint:1.0
        container_name: protected_endpoint_container
        networks:
            - kong-net
        depends_on:
            - rabbitmq
        restart: always

    bubble-details:
        build:
            context: ./BubbleDetails
        environment:
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            PYTHONUNBUFFERED: 1
        image: bubble-details:1.0
        container_name: bubble_details_container
        networks:
            - kong-net
        depends_on:
            - mysqldb

    bubble-roles:
        build:
            context: ./BubbleRole
        environment:
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            PYTHONUNBUFFERED: 1
        image: bubble-roles:1.0
        container_name: bubble_roles_container
        networks:
            - kong-net
        depends_on:
            - mysqldb

    bubble-files:
        build:
            context: ./BubbleFile
        environment:
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            PYTHONUNBUFFERED: 1
        image: bubble-files:1.0
        container_name: bubble_files_container
        networks:
            - kong-net
        depends_on:
            - mysqldb

    bubble-activity:
        build:
            context: ./BubbleActivity
        environment:
            PYTHON_ENV: PROD
            PYTHONUNBUFFERED: 1
        image: bubble-activity:1.0
        container_name: bubble_activity_container
        networks:
            - kong-net
        depends_on:
            - mysqldb

    module:
        build:
            context: ./Module
        environment:
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            PYTHONUNBUFFERED: 1
        image: module:1.0
        container_name: module_container
        networks:
            - kong-net
        depends_on:
            - mysqldb

    module-verification:
        build:
            context: ./ModuleVerification
        environment:
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            PYTHONUNBUFFERED: 1
        image: module-verification:1.0
        container_name: module_verification_container
        networks:
            - kong-net
        depends_on:
            - mysqldb

    bubble:
        build:
            context: ./Bubble
        environment:
            RABBITMQ_HOSTNAME: "rabbitmq"
            RABBITMQ_PORT: "5672"
            PYTHON_ENV: PROD
            dbURL: "mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}"
            PYTHONUNBUFFERED: 1
        image: bubble:1.0
        container_name: bubble_container
        networks:
            - kong-net
        depends_on:
            - rabbitmq
        restart: always